# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-27 16:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='story',
            field=models.ForeignKey(blank=True, default=b'', on_delete=django.db.models.deletion.CASCADE, to='news.Story'),
        ),
    ]
